version: '3.8'
services:
  webp_converter:
    image: node:22.14.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173" # Vite development server
      - "4173:4173" # Vite preview server
    command: "npm run dev"
